[package]
name = "pgn2csv"
version = "0.1.0"
edition = "2021"
authors = ["jmviz"]

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
pgn-reader = "0.19.0"
bzip2 = "0.4.3"
humantime = "2.1.0"
regex = "1"
lazy_static = "1.4.0"
globwalk = "0.8.1"
rayon = "1.5"